<?php

require_once(__DIR__ . './../../config.php');
require_once($CFG->libdir . '/externallib.php');

$userid = required_param('userid', PARAM_INT);  // The user id the key belongs to (for double-checking).
$key = required_param('key', PARAM_ALPHANUMEXT);    // The key generated by the tool_mobile_external::get_autologin_key() external function.
$urltogo = optional_param('urltogo', $CFG->wwwroot, PARAM_URL);    // URL to redirect.

$context = context_system::instance();
$PAGE->set_context($context);

// Check if the user is already logged-in.
if (isloggedin() and !isguestuser()) {
    delete_user_key('local_wsqisat', $userid);
    if ($USER->id == $userid) {
        redirect($urltogo);
    } else {
        throw new moodle_exception('alreadyloggedin', 'error', '', format_string(fullname($USER)));
    }
}

// begin function tool_mobile\api::check_autologin_prerequisites($userid);
if (!$CFG->enablewebservices or !$CFG->enablemobilewebservice) {
    throw new moodle_exception('enablewsdescription', 'webservice');
}

if (!is_https()) {
    throw new moodle_exception('httpsrequired', 'local_wsqisat');
}

if (has_capability('moodle/site:config', context_system::instance(), $userid) or is_siteadmin($USER->id)) {
    throw new moodle_exception('autologinnotallowedtoadmins', 'local_wsqisat');
}
// end function tool_mobile

// Validate and delete the key.
$key = validate_user_key($key, 'local_wsqisat', null);
delete_user_key('local_wsqisat', $userid);

// Double check key belong to user.
if ($key->userid != $userid) {
    throw new moodle_exception('invalidkey');
}

// Key validated, now require an active user: not guest, not suspended.
$user = core_user::get_user($key->userid, '*', MUST_EXIST);
core_user::require_active_user($user, true, true);

// Do the user log-in.
if (!$user = get_complete_user_data('id', $user->id)) {
    throw new moodle_exception('cannotfinduser', '', '', $user->id);
}

complete_user_login($user);
\core\session\manager::apply_concurrent_login_limit($user->id, session_id());

redirect($urltogo);
