<?php

$string['pluginname'] = 'Web service QiSat';

$string['testmessagedescription'] = 'The text begin from message. By default it is "Hello world, (USER FIRSTNAME)"';
$string['testmessagereturn'] = 'The message + user first name';

$string['getautologinkeydescription'] = 'Private token, usually generated by login/token.php';
$string['getautologinkeyreturnkey'] =  'Auto-login key for a single usage with time expiration.';
$string['getautologinkeyreturnurl'] = 'Auto-login URL.';
$string['autologinkeygenerationlockout'] = 'Auto-login key generation is blocked. You need to wait 6 minutes between requests.';
$string['autologinnotallowedtoadmins'] = 'Auto-login is not allowed for site admins.';
$string['invalidprivatetoken'] = 'Invalid private token. Token should not be empty or passed via GET parameter.';
$string['httpsrequired'] = 'HTTPS required';
$string['getusername'] = 'Returns the user name of the logged in user';